### ISSUE TITLE
Assets referenced from resources folder are removed

### ISSUE THREAD

**Issue by itsmesaskovic** [swiftmade/statamic-clear-assets#6]
Thanks for the addon first of all! 

Was testing it on our developer branch and I noticed that it only checks the **content** folder.
In our case we are also referencing assets from our resources folder. (Yes, some parts are hardcoded :-) )

Adding the resources folder in filterUnused did the trick for us.

One additional thing we found is that assets referenced via an svg tag are not found.
Like: `{{ svg src="/assets/logo/nofam-logo-horizontal-top" class="logo-header"`

**Comment by aozisik** [comment]
Hi @itsmesaskovic,

Thanks for reporting this.

I guess we could add a config file where package users can declare their own "scan" paths.

> One additional thing we found is that assets referenced via an svg tag are not found.

I guess because the package looks for `filename.svg` whereas in the template it's `{{ svg src=".../filename"`. The solution could be for you to include the `.svg` extension. It looks like Statamic will find the asset with or without the extension.

**Comment by aozisik** [comment]
Hi @itsmesaskovic,

It's been a while, but if you are still using this package, now there's a bunch of configuration options that might help you address this.

First of all, you can now add your "resource" folder to scan paths if you're referencing assets from your antlers templates. In your example, you use the svg tag, so you omit the svg extension. I suggest adding the svg extension as well so that the path matches with the asset name.

More on the latest release:
https://github.com/swiftmade/statamic-clear-assets/releases/tag/v1.2.0
